---
- name: Copy specific log files from remote machine to control machine
  hosts: all
  gather_facts: no
  tasks:
      - name: Check if log files are readable and gather their content
        command: cat /var/log/{{ item }}
        register: log_file_contents
        ignore_errors: yes
        with_items:
            - boot.log
            - syslog
            - dpkg.log
            - kern.log

      - name: Get lastlog command output
        command: lastlog
        register: lastlog_output
        ignore_errors: yes

      - name: Get faillog command output
        command: faillog
        register: faillog_output
        ignore_errors: yes

      - name: Create a map of log file contents
        set_fact:
            logs_map: "{{ logs_map | default({}) | combine({item.item: item.stdout}) }}"
        with_items: "{{ log_file_contents.results }}"
        when: item.stdout is defined and item.stdout != ""

      - name: Add lastlog output to the map
        set_fact:
            logs_map: "{{ logs_map | combine({'lastlog': lastlog_output.stdout}) }}"
        when: lastlog_output.stdout is defined and lastlog_output.stdout != ""

      - name: Add faillog output to the map
        set_fact:
            logs_map: "{{ logs_map | combine({'faillog': faillog_output.stdout}) }}"
        when: faillog_output.stdout is defined and faillog_output.stdout != ""

      - name: Save the logs map to a file
        copy:
            content: "{{ logs_map | to_nice_json }}"
            dest: /tmp/logs_map.json
        delegate_to: localhost

