- name: Gather installed applications on host machine
  hosts: all
  gather_facts: yes
  tasks:
      - name: Gather installed applications on Debian-based systems
        command: dpkg-query -W -f='${Package} ${Version} ${Installed-Size}\n'
        when: ansible_facts['os_family'] == "Debian"
        register: packages
        ignore_errors: yes

      - name: Print installed applications
        debug:
            var: packages

