- name: Check IPMI SEL logs for errors
  hosts: all
  gather_facts: no
  tasks:
      - name: Fetch SEL logs
        ipmi_sel:
            user: "{{ ansible_user }}"
            password: "{{ ansible_become_password }}"
        register: sel_logs

      - name: Print SEL logs
        debug:
            var: sel_logs

