#! Change in the keys here will need to be reflected in the 'static/scripts/host.js' file
---
- name: Collect system information from all hosts in the inventory
  hosts: all
  gather_facts: yes
  tasks:
      - name: Get peripheral information
        include_tasks: peripherals_tasks.yml

      - name: Get platform information
        set_fact:
            platform_info:
                system: "{{ ansible_system }}"
                release: "{{ ansible_distribution_release }}"
                architecture: "{{ ansible_architecture }}"
                type: "{{ ansible_machine }}"
                version: "{{ ansible_distribution_version }}"
                hostname: "{{ ansible_hostname }}"
                uptime: "{{ ansible_uptime_seconds }}"
                users: "{{ ansible_user_id }}"
                cpus: "{{ ansible_processor }}"
                mem_total: "{{ (ansible_memory_mb.real.total | int * 1048576) | human_readable }}"
                mem_used: "{{ (ansible_memory_mb.real.used | int * 1048576) | human_readable }}"
                mem_free: "{{ (ansible_memory_mb.real.free | int * 1048576) | human_readable }}"
                disk_total: "{{ ansible_mounts[0].size_total | human_readable }}"
                disk_free: "{{ ansible_mounts[0].size_available | human_readable }}"
                disk_used: "{{ (ansible_mounts[0].size_total - ansible_mounts[0].size_available) | int | human_readable }}"
                cores: "{{ ansible_processor_nproc }}"
                default_ip: "{{ ansible_default_ipv4.address | default('N/A') }}"
                network_interfaces: "{{ ansible_interfaces }}"
                mac_addresses: "{{ ansible_default_ipv4.macaddress | upper }}"
                ipv4_addresses: "{{ ansible_all_ipv4_addresses }}"
                ipv6_addresses: "{{ ansible_all_ipv6_addresses }}"
                dns_servers: "{{ ansible_dns.nameservers }}"
                gateway: "{{ ansible_default_ipv4.gateway }}"
                domain: "{{ ansible_domain }}"
                timezone: "{{ ansible_date_time.tz }}"
                peripheral_devices: "{{ peripherals }}"
                locale: "{{ ansible_env.LANG }}"
                python_version: "{{ ansible_python_version }}"

      - name: Print collected information
        debug:
            var: platform_info

