- name: Uninstall applications and their dependencies
  become: yes
  hosts: all
  tasks:
      - name: Remove apt package
        apt:
            name: "{{ item }}"
            state: absent
            purge: yes
        loop: "{{ app_list }}"
        ignore_errors: yes

      - name: Autoremove unnecessary dependencies
        apt:
            autoremove: yes
            state: latest

