- name: Uninstall applications and their dependencies
  become: yes
  hosts: all
  tasks:
      - name: Gather facts about installed packages
        package_facts:

      - name: Remove apt package
        apt:
            name: "{{ item }}"
            state: absent
            purge: yes
        loop: "{{ app_list }}"
        ignore_errors: yes
        when: "item in ansible_facts.packages"

      - name: Autoremove unnecessary dependencies
        apt:
            autoremove: yes
            state: latest

