---
- name: Wake on Lan
  gather_facts: no
  hosts: local
  tasks:
      - name: Send WoL packet
        community.general.wakeonlan:
            mac: "{{ mac_address }}"
            broadcast: "{{ broadcast_address }}"
            port: 9
