---
- name: Wake on Lan
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Send WoL packet
      community.general.wakeonlan:
        mac: "{{ mac_address }}"
        broadcast: "{{ broadcast_address }}"