# Generated by Django 5.0.7 on 2024-08-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200)),
                ('command', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('host_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('system', models.CharField(max_length=100)),
                ('release', models.CharField(max_length=100)),
                ('architecture', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('uptime', models.BigIntegerField()),
                ('users', models.CharField(blank=True, max_length=100)),
                ('cpus', models.JSONField()),
                ('mem_total', models.CharField(max_length=50)),
                ('mem_free', models.CharField(max_length=50)),
                ('mem_used', models.CharField(max_length=50)),
                ('disk_total', models.CharField(max_length=100)),
                ('disk_used', models.CharField(max_length=100)),
                ('disk_free', models.CharField(max_length=100)),
                ('cores', models.IntegerField()),
                ('default_ip', models.CharField(max_length=50)),
                ('network_interfaces', models.JSONField()),
                ('mac_addresses', models.CharField(max_length=100)),
                ('ipv4_addresses', models.JSONField()),
                ('ipv6_addresses', models.JSONField()),
                ('dns_servers', models.JSONField()),
                ('gateway', models.CharField(max_length=100)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(max_length=50)),
                ('peripheral_devices', models.JSONField()),
                ('locale', models.CharField(max_length=50)),
                ('python_version', models.CharField(max_length=50)),
            ],
        ),
    ]
