# Generated by Django 5.0.4 on 2024-07-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_app_command'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='command',
            new_name='package',
        ),
    ]
