# Generated by Django 5.0.4 on 2024-07-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_command_app_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='package',
            new_name='command',
        ),
        migrations.AddField(
            model_name='app',
            name='package_name',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='version',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
