# Generated by Django 5.0.7 on 2024-07-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_systeminfo_host_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systeminfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='host_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
