# Generated by Django 5.0.4 on 2024-07-11 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
